version: '3.4'


services:
  Mercado:
    image: Mercado
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:80
    depends_on:
      -db


  db:
    image: postgres
    restart: always
    container_name: bdclientes
    environment:
      POSTGRES_DB: clientes
      POSTGRES_USER: diegomb
      POSTGRES_PASSWORD: DDD111+
    volumes:
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - 5432:5432
    depends_on:
      -Mercado
